### PR TITLE
Fix CPU spin in marshaled item processing

### PR DESCRIPTION
**Pull request by jcorbin**

### CODE REVIEW

**Comment by phungs** [comment]
@jcorbin lgtm

Code optimization suggestion: We could get rid of the loop label and make the break and continue stmts non-label versions without altering functionality.

**Comment by jcorbin** [comment]
Done, the loop label isn't needed anymore since we don't need to break out of loop from within a switch case anymore.

**Comment by phungs** [comment]
lgtm

**Review by phungs — APPROVED** [review]
lgtm

**Pull request merged**
